// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearErrorLogs():Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetErrorLogs():Promise<string>;

export function GetTasks():Promise<Array<main.CleanTask>>;

export function RunTaskNow(arg1:string):Promise<main.TaskResult>;

export function SaveTask(arg1:main.CleanTask):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;
