// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearErrorLogs() {
  return window['go']['main']['App']['ClearErrorLogs']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetErrorLogs() {
  return window['go']['main']['App']['GetErrorLogs']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function RunTaskNow(arg1) {
  return window['go']['main']['App']['RunTaskNow'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['main']['App']['SaveTask'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
